/**
 * WhiteboardService — in-memory per-room state.
 *
 * ── Room Lifecycle (Security-Critical) ───────────────────────────────────────
 *
 * Rooms are now EXPLICITLY created via createRoom() before any user can join.
 * This is the server-side gate that prevents ID enumeration:
 *
 *   Old flow: room:join { roomId: "ABC" } → getOrCreateRoom("ABC") → always succeeds
 *   New flow: room:join { roomId: "<uuid>" } → getRoom("<uuid>") → null if never created
 *
 * The UUID is generated by the server (POST /api/rooms) using crypto.randomUUID(),
 * so the client can never invent a valid room ID — it must have received one from us.
 *
 * ── Collaborative Global Undo/Redo ───────────────────────────────────────────
 *
 * Every room owns ONE shared `actionHistory` (undo stack) and `redoStack`.
 * Any user can undo or redo any action performed by any other user.
 *
 * Action types:
 *   { type: 'stroke', stroke, performedBy }          — a committed drawing stroke
 *   { type: 'clear',  previousStrokes, performedBy } — board-clear with snapshot
 *
 * ── Horizontal Scalability ───────────────────────────────────────────────────
 *
 * Replace `rooms` Map with Redis hashes + Pub/Sub for cross-process broadcast.
 * Add @socket.io/redis-adapter for Socket.io room membership.
 * Handler code is unchanged — the service interface is the DB boundary.
 */

import { config } from '../config/env.js';

/** @typedef {{ userId:string, username:string }} Attribution */
/** @typedef {{ type:'stroke'|'clear', stroke?:object, previousStrokes?:object[], performedBy:Attribution }} Action */
/** @typedef {{ id:string, strokes:object[], actionHistory:Action[], redoStack:Action[], users:Map, createdAt:string, updatedAt:string }} Room */

/** @type {Map<string, Room>} */
const rooms = new Map();

const makeRoom = (roomId) => ({
  id:            roomId,
  strokes:       [],
  actionHistory: [],
  redoStack:     [],
  users:         new Map(),
  createdAt:     new Date().toISOString(),
  updatedAt:     new Date().toISOString(),
});

const touch = (room) => { room.updatedAt = new Date().toISOString(); return room; };

const trimHistory = (room) => {
  if (room.actionHistory.length > config.historyLimit) {
    room.actionHistory.splice(0, room.actionHistory.length - config.historyLimit);
  }
};

const historyResult = (room, lastAction) => ({
  strokes:    [...room.strokes],
  canUndo:    room.actionHistory.length > 0,
  canRedo:    room.redoStack.length > 0,
  lastAction,
});

export const whiteboardService = {

  // ── Room lifecycle ──────────────────────────────────────────────────────────

  /**
   * Explicitly create a new room with the given ID.
   * Called ONLY from the REST controller (POST /api/rooms).
   * The ID is a UUID v4 generated by the server — never by the client.
   * Returns null if the room already exists (idempotent guard).
   */
  createRoom(roomId) {
    if (rooms.has(roomId)) return null;          // already exists — don't overwrite
    const room = makeRoom(roomId);
    rooms.set(roomId, room);
    return room;
  },

  getRoom(roomId) {
    return rooms.get(roomId) ?? null;
  },

  // ── Stroke mutations ────────────────────────────────────────────────────────

  addStroke(roomId, stroke, performedBy) {
    const room = this.getRoom(roomId);
    if (!room) return null;                      // room must exist; never auto-create
    room.strokes.push(stroke);
    room.actionHistory.push({ type: 'stroke', stroke, performedBy });
    room.redoStack = [];
    trimHistory(room);
    touch(room);
    return stroke;
  },

  // ── Clear (undoable) ────────────────────────────────────────────────────────

  clearRoom(roomId, performedBy) {
    const room = this.getRoom(roomId);
    if (!room) return;
    room.actionHistory.push({
      type:            'clear',
      previousStrokes: [...room.strokes],
      performedBy,
    });
    room.redoStack = [];
    room.strokes   = [];
    trimHistory(room);
    touch(room);
  },

  // ── Undo ────────────────────────────────────────────────────────────────────

  undo(roomId, performedBy) {
    const room = this.getRoom(roomId);
    if (!room || room.actionHistory.length === 0) return null;

    const action = room.actionHistory.pop();
    room.redoStack.push(action);

    if (action.type === 'stroke') {
      const idx = room.strokes.map((s) => s.id).lastIndexOf(action.stroke.id);
      if (idx !== -1) room.strokes.splice(idx, 1);
    } else if (action.type === 'clear') {
      room.strokes = [...action.previousStrokes];
    }

    touch(room);
    return historyResult(room, { type: 'undo', action, performedBy });
  },

  // ── Redo ────────────────────────────────────────────────────────────────────

  redo(roomId, performedBy) {
    const room = this.getRoom(roomId);
    if (!room || room.redoStack.length === 0) return null;

    const action = room.redoStack.pop();
    room.actionHistory.push(action);
    trimHistory(room);

    if (action.type === 'stroke') {
      room.strokes.push(action.stroke);
    } else if (action.type === 'clear') {
      room.strokes = [];
    }

    touch(room);
    return historyResult(room, { type: 'redo', action, performedBy });
  },

  // ── Queries ─────────────────────────────────────────────────────────────────

  getHistoryState(roomId) {
    const room = this.getRoom(roomId);
    if (!room) return { canUndo: false, canRedo: false };
    return {
      canUndo: room.actionHistory.length > 0,
      canRedo: room.redoStack.length > 0,
    };
  },

  getStrokes(roomId) {
    const room = this.getRoom(roomId);
    return room ? [...room.strokes] : [];
  },

  // ── User management ─────────────────────────────────────────────────────────

  /**
   * Add a user to an EXISTING room.
   * Returns null (not the room) if the room does not exist.
   * This is the server-side enforcement point: you cannot join a room
   * that was never created via POST /api/rooms.
   */
  addUser(roomId, user) {
    const room = this.getRoom(roomId);
    if (!room) return null;                      // room must have been explicitly created
    room.users.set(user.id, user);
    touch(room);
    return room;
  },

  removeUser(roomId, userId) {
    const room = this.getRoom(roomId);
    if (!room) return null;
    room.users.delete(userId);
    touch(room);
    // Schedule GC: delete the room 30s after the last user leaves
    if (room.users.size === 0) {
      setTimeout(() => {
        const r = rooms.get(roomId);
        if (r && r.users.size === 0) rooms.delete(roomId);
      }, 30_000);
    }
    return room;
  },

  getRoomUsers(roomId) {
    const room = this.getRoom(roomId);
    return room ? Array.from(room.users.values()) : [];
  },

  findUser(roomId, userId) {
    const room = this.getRoom(roomId);
    return room?.users.get(userId) ?? null;
  },

  listRooms() {
    return Array.from(rooms.values()).map((r) => ({
      id:           r.id,
      userCount:    r.users.size,
      strokeCount:  r.strokes.length,
      historyDepth: r.actionHistory.length,
      redoDepth:    r.redoStack.length,
      createdAt:    r.createdAt,
      updatedAt:    r.updatedAt,
    }));
  },
};