import { z } from 'zod';
import { config } from '../../config/env.js';
import { UUID_V4_RE } from '../../middleware/validateRequest.js';

const { width: CW, height: CH } = config.canvas;

// ── Primitives ────────────────────────────────────────────────────────────────

const coord = z.object({
  x: z.number().finite().min(-10).max(CW + 10),
  y: z.number().finite().min(-10).max(CH + 10),
});

const hexColor = z
  .string()
  .regex(/^#[0-9a-fA-F]{3}([0-9a-fA-F]{3})?$/, 'Invalid hex color')
  .default('#1A1814');

const tool = z.enum(['pen', 'eraser', 'line', 'rect', 'circle']);

const strokeId = z
  .string()
  .min(1)
  .max(32)
  .regex(/^[a-z0-9]+$/, 'Invalid stroke ID');

const pointsArray = z.array(coord).min(1).max(10_000);

// ── Stroke base ───────────────────────────────────────────────────────────────

const baseStroke = z.object({
  id:         strokeId,
  tool,
  color:      hexColor,
  lineWidth:  z.number().finite().min(1).max(200).default(3),
  opacity:    z.number().finite().min(0).max(1).default(1),
  eraserSize: z.number().finite().min(1).max(400).optional(),
});

// draw:start is ephemeral — ID has not been generated yet at stroke-start time.
const baseStrokeNoId = z.object({
  tool,
  color:      hexColor,
  lineWidth:  z.number().finite().min(1).max(200).default(3),
  opacity:    z.number().finite().min(0).max(1).default(1),
  eraserSize: z.number().finite().min(1).max(400).optional(),
});

// ── Exported schemas ──────────────────────────────────────────────────────────

export const freehandStrokeSchema = baseStroke.extend({ points: pointsArray });
export const shapeStrokeSchema    = baseStroke.extend({ startPoint: coord, endPoint: coord });

export const drawEndSchema = z.union([freehandStrokeSchema, shapeStrokeSchema]);

export const drawStartSchema = z.union([
  baseStrokeNoId.extend({ points:     pointsArray }),
  baseStrokeNoId.extend({ startPoint: coord }),
]);

export const drawMoveSchema = z.object({ point: coord });

// ── Room schemas ──────────────────────────────────────────────────────────────

export const roomJoinSchema = z.object({
  /**
   * Room ID is now a UUID v4 — server-generated, cryptographically random.
   * The strict regex (version nibble = 4, variant nibble ∈ {8,9,a,b}) means
   * only IDs that were actually generated by crypto.randomUUID() can match.
   * A client cannot invent a passing roomId — it must have received one from
   * POST /api/rooms.
   */
  roomId: z
    .string()
    .regex(UUID_V4_RE, 'Invalid room ID — must be a UUID v4'),

  username: z
    .string()
    .min(1)
    .max(32)
    .transform((s) => s.replace(/[<>"'&;()\\/]/g, '').trim())
    .pipe(z.string().min(1, 'Username empty after sanitization')),
});

export const cursorMoveSchema = coord;

// ── Parse helper ──────────────────────────────────────────────────────────────

export const safeParse = (schema, data, label = '') => {
  const result = schema.safeParse(data);
  if (!result.success) {
    if (config.isDev) {
      console.warn(`[validation] ${label}:`, result.error.flatten().fieldErrors);
    }
    return null;
  }
  return result.data;
};